name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 8.0
          version: 2

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
#        env:
#          TEST_NAME: Scarlett
        with:
          php_version: 8.0
          version: 9
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml.dist
          args: --coverage-text
